### ISSUE TITLE
Create REST endpoint for todo lists

### ISSUE THREAD

**Issue by jChris85** [jChris85/spring-boot-todo-app#11]
Create a REST controller for todo lists

- [ ] create new todo list
- [ ] delete todo list
- [ ] update todo list name
