### ISSUE TITLE
Create todo app layout

### ISSUE THREAD

**Issue by jChris85** [jChris85/spring-boot-todo-app#2]
Create a layout for a todo web app.

The app should have the following features:

- [ ] add new todos with custom description
- [ ] edit todo description of existing todos
- [ ] mark todos as completed
- [ ] filter todos (status: open, all, completed)
- [ ] delete all completed todos

Add the layout (source and jpg) to a folder assets on the root level

**Comment by marekgebka** [comment]
I'll do it!
