### ISSUE TITLE
build a REST api for todo management

### ISSUE THREAD

**Issue by jChris85** [jChris85/spring-boot-todo-app#4]
Build a REST api to manage the todos.

The api should have the following REST endpoints:

- [x] create new todo
- [x] get all todos
- [x] update existing todo
- [x] delete todo

Endpoint proposals:

- PUT: /todo
- GET: /todos
- POST: /todo/{:id}
- DELETE: /todo/{:id}
